//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yetic_MeLo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsSet
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string Extension { get; set; }
        public bool Check { get; set; }
    }
}
