//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetiMelo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folders
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public bool Music { get; set; }
        public bool Picture { get; set; }
        public bool Video { get; set; }
    }
}
